name: User Story
description: User Feature Story
title: "[Story]: "
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        As a [persona], I [want to], [so that].
  - type: input
    id: as-a
    attributes:
      label: As a...
      description: Who are we building this for? We’re not just after a job title, we’re after the persona of the person. Max. Our team should have a shared understanding of who Max is. We’ve hopefully interviewed plenty of Max’s. We understand how that person works, how they think and what they feel. We have empathy for Max. [More info](https://www.atlassian.com/agile/project-management/user-stories).
      placeholder: member of the development team
    validations:
      required: true
  - type: input
    id: wants-to
    attributes:
      label: Wants to...
      description: Here we’re describing their intent — not the features they use. What is it they’re actually trying to achieve? This statement should be implementation free — if you’re describing any part of the UI and not what the user goal is you're missing the point. [More info](https://www.atlassian.com/agile/project-management/user-stories).
      placeholder: understand my colleagues progress
    validations:
      required: true
  - type: input
    id: so-that
    attributes:
      label: So that...
      description: How does their immediate desire to do something this fit into their bigger picture? What’s the overall benefit they’re trying to achieve? What is the big problem that needs solving? [More info](https://www.atlassian.com/agile/project-management/user-stories).
      placeholder: better report our sucess and failures
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: This is something that can be verified to show that this user story is satisfied. This is typically written in first person point of view.
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: Any other additional resources you have that you might want to link.
      placeholder: Documentation, style guides, email references, templates, etc.
    validations:
      required: false

