name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: lryanle
          repo: seniordesign
          filename: 
          config_timezone: US/Central
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_projects: yes
          plugin_projects_repositories: lryanle/seniordesign/projects/2
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://smare.lryanle.com
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.smarescreenshot.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: SMARE Site
          plugin_screenshot_url: https://smare.lryanle.com